name: Windows Build, Test, and Pack

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_test_pack:
    name: Build (Release), Test (Debug), Pack
    runs-on: windows-latest
    timeout-minutes: 60
    env:
      DOTNET_NOLOGO: true
      NUGET_PACKAGES: ${{ github.workspace }}\.nuget\packages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # full history helps when packing with SourceLink/RepositoryCommit
          fetch-depth: 0

      - name: Setup .NET SDK (8.x)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.lock.json', '**/*.csproj', 'Directory.Packages.props') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Restore (solution)
        run: dotnet restore .\HostBridge.sln

      - name: Build src (Release, warn-as-error)
        shell: pwsh
        run: |
          Get-ChildItem .\src -Recurse -Filter *.csproj | ForEach-Object {
            Write-Host "Building $($_.FullName)"
            dotnet build $_.FullName -c Release --no-restore -warnaserror
          }

      - name: Test (Debug) - all test projects
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $projects = Get-ChildItem .\tests -Recurse -Filter *.csproj | ForEach-Object { $_.FullName }
          foreach ($p in $projects) {
            Write-Host "Testing $p"
            dotnet test $p -c Debug --no-build --logger "trx;LogFileName=$(Split-Path -LeafBase $p).trx"
          }

      # Pack for validation on all events; only upload artifacts on push (not PR)
      - name: Pack src (Release)
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path .\artifacts\nuget | Out-Null
          Get-ChildItem .\src -Recurse -Filter *.csproj | ForEach-Object {
            Write-Host "Packing $($_.FullName)"
            dotnet pack $_.FullName -c Release --no-build -o .\artifacts\nuget
          }

      - name: Upload NuGet artifacts (pushes only)
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: artifacts/nuget/*.nupkg
          if-no-files-found: error
          retention-days: 7

      # Dependency review works on public repos; harmless on private (no-op).
      - name: Dependency Review (PRs only, public repos)
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@v4

  publish:
    name: Publish to NuGet.org
    runs-on: windows-latest
    needs: build_test_pack
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuget-packages
          path: artifacts/nuget

      - name: Setup .NET SDK (8.x)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Push packages to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        shell: pwsh
        run: |
          if (-not $env:NUGET_API_KEY) { throw 'Missing NUGET_API_KEY secret' }
          Get-ChildItem .\artifacts\nuget -Filter *.nupkg | ForEach-Object {
            Write-Host "Pushing $($_.Name)"
            dotnet nuget push $_.FullName --api-key $env:NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
          }
